#!/bin/bash

function usage() {
    echo "plugin_wrapper PLUGIN_NAME COMMAND [COMMAND_ARG1] [COMMAND_ARG2] [...]"
}

if test "${1:-}" = "--help"; then
    usage
    exit 0
fi
if test "${1:-}" = "-h"; then
    usage
    exit 0
fi
if test "${1:-}" = ""; then
    usage
    exit 1
fi

PLUGIN_NAME=${1:-}
shift

set -x

exec layer_wrapper --empty --extra-env-prefix="${MODULE}_CURRENT_PLUGIN" --layers="plugin_${PLUGIN_NAME}@${MODULE_LOWERCASE}" -- $@
